version: '3.7'
networks:
  default:
      name: rodsstar
services:
  postgres_db:
    image: postgres
    container_name: postgres_db
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: docker